feat: matrices

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -6,15 +6,35 @@ jobs:
         name: ${{ matrix.os }}-${{ matrix.node-version }}
         runs-on: ${{ matrix.os }}
         strategy:
+            fail-fast: false
             matrix:
                 node-version: [24.x, 26.x]
-                os: [ubuntu-latest, windows-latest]
+                os:
+                    - ubuntu-latest
+                    - windows-latest
+                include:
+                    - os: ubuntu-latest
+                      node-version: 24.x
+                    - os: ubuntu-latest
+                      node-version: 26.x
+                      tag: experimental
         steps:
             - name: "Set up Node.js"
               uses: actions/setup-node@v6
               with:
                   node-version: ${{ matrix.node-version }}
-                        
+            
+            - name: "Fail if experimental"
+              if: ${{ matrix.tag == 'experimental' }}
+              run: |
+                  echo "This is an experimental build and will fail."
+                  exit 1
+
             - name: "Perform some tests"
               run: |
-                  echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
+                sleep 10
+                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
+            
+            - name: "Upload test results"
+              run: |
+                echo "Uploading test results for OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
